### ISSUE TITLE
Set up repositories for all attendees

### ISSUE THREAD

**Issue by nickstenning** [codessintheclassroom/classroom-material#21]
We need to set up N personal repositories for our attendees. At a minimum, these should contain:

- a very basic readme
- a `frontend/` folder (with an empty `.gitkeep` inside)

The plan is to make repositories with names like `<adjective>-<pet name>`: `happy-rover`, `bouncy-ginger`, `lazy-snoopy`, etc.

**Comment by msft-igore** [comment]
Don't add .gitkeep as this will will create a conflict with 'npx create-react-app . --typescript'

**Comment by nickstenning** [comment]
If we want the folder to exist already (which I have a mild preference for, as it will reduce the chance that people create the app in the repo root) then we need _a_ file there. It looks like [an empty `.gitignore` should work instead](https://github.com/facebook/create-react-app/blob/57ef103440c24e41b0d7dc82b7ad7fc1dc817eca/packages/create-react-app/createReactApp.js#L792-L809).

**Comment by nickstenning** [comment]
All done!
