### ISSUE TITLE
git setup

### ISSUE THREAD

**Issue by msft-igore** [codessintheclassroom/classroom-material#27]
To avoid confusion with git first-timers, it might make sense to add the installation steps to avoid line break sequence warnings.
Additionally it makes sense to add the git global variables with name and email address before first commit:
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

**Comment by nickstenning** [comment]
:+1:

1. Line breaks: https://github.com/codessintheclassroom/workshop-scaffold/blob/3ef077f7246ca030924ef0c2523d4210f474c2a2/.gitattributes
2. First-time git setup: 93cc7bc
