### ISSUE TITLE
Evaluate options for state management in the web client

### ISSUE THREAD

**Issue by stirlaf** [codessintheclassroom/classroom-material#4]
Look at different options and suggest something that would be very simple for attendees to implement or consider a pre-built option that they can integrate and consume if all options are too complex for implementation from scratch.

**Comment by nickstenning** [comment]
Do you think we can get away with limited/no state management? 

If we stick to just asking folks to put together a) a list view, driven by the collection API, and b) a pet detail view, driven by the pet detail API, would it be feasible to avoid having to explain (say) redux in the context of this workshop? You're the expert, I merely want us to keep this as simple as possible -- we have only an hour for the coding part of the workshop :)

**Comment by stirlaf** [comment]
@nickstenning, Agreed that this should be super basic.  This may just be terminology mismatch as well.  I would consider calling setState and accessing this.state in a react component as a form of state management as well, even though it's super basic.  Check out the current version of App.tsx which uses this behavior, and let me know if that allays your concerns.

**Comment by nickstenning** [comment]
Guessing we can close this now? Feel free to reopen if I've misunderstood... 🙂
