### ISSUE TITLE
Add detailed instructions on adding unit tests, plus sample unit tests and tests cases.

### ISSUE THREAD

**Issue by stirlaf** [codessintheclassroom/classroom-material#6]
Add to:
https://github.com/codessintheclassroom/classroom-material/blob/master/week1-webclient.md

This should also include instructions on configuring vscode to debug the unit tests. i.e. adding the following launch config:

        {
            "name": "Debug create react app Tests",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts",
            "args": [
              "test",
              "--runInBand",
              "--no-cache",
              "--no-watch"
            ],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }

**Comment by nickstenning** [comment]
Closing thanks to @stirlaf's work in #13.
