### ISSUE TITLE
Write intro/setup guide

### ISSUE THREAD

**Issue by nickstenning** [codessintheclassroom/classroom-material#8]
Write the course material for the first part of the workshop. It should cover, roughly:

- Finding and cloning their git repository (we'll be precreating one git repository per attendee)
- Creating a branch on which to do their work
- Bootstrapping the react app (with `create-react-app`... currently documented in `week1-webclient.md`).

**Comment by pviotti** [comment]
Note: create react app in the client subdirectory

**Comment by nickstenning** [comment]
Closed by #16. Thank you @suzanapescador! 🙇
